### ISSUE TITLE
Lag when clicking on a radio button

### ISSUE THREAD

**Issue by nii236** [pzi/simple-todo-webapp#8]
There is a lag when checking or unchecking a todo item. This is probably due to the AJAX request completing before you update the `completed` state.

**Comment by levibuzolic** [comment]
You've got a few options here:

 1. You can set an intermediate state which is then resolved when the server response is completed. That way the user sees some response to their click, but they can tell that the state is pending.
 2. Optimistically set the state before the server responds, then debounce the request to prevent race conditions.

**Comment by pzi** [comment]
I prefer option 1.

The lag comes from cross origin http request. When you watch the XHR panel in devtools it will send out 2 requests. OPTIONS first and then the actual PATCH. So it's preflighting the patch. And given the server is somewhere else in the world it will take a while because the response time just doubled.

**Comment by nii236** [comment]
Doesn't option 1 mean you need to maintain two states? Client side and server side then resolve the two when the response returns?

**Comment by levibuzolic** [comment]
Option 1 would be the same state, but with 3 possible values instead of 2.

`checked: (true|false|'pending')`

**Comment by levibuzolic** [comment]
Alternatively you could use a new state like `pending: true/false`

**Comment by nii236** [comment]
:+1:

**Comment by pzi** [comment]
So it would be a defaultState of `pending: false` and `onClick`, update `pending: true` until the xhr has completed then revert back.
